services:
  ngrok:
    image: ngrok/ngrok:latest@sha256:1d5daa80665b74694dc9804dd64a59da0defea910fe7799ab380e52483aeca1c
    command: http --url=${NGROK_SUBDOMAIN} grafana:3000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  grafana:
    image: grafana/grafana:main@sha256:a0183bc04e65bfd70850895c637e940e28632ec6342bd041cfa1110856e5251d
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=provisioning,kubernetesDashboards
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_SERVER_ROOT_URL=https://${NGROK_SUBDOMAIN}

    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - renderer
      - ngrok
    restart: unless-stopped
  renderer:
    image: grafana/grafana-image-renderer:latest@sha256:340c91e98ccd65001a3da4d0192fcf0ed13e95609a51a0d62c35a61b6ff28dff
    ports:
      - 8081

volumes:
  grafana-data:
